from __future__ import annotations

import json
from pathlib import Path
from typing import Any


OUTPUTS_DIR = Path("outputs")
LIBRARY_DIR = Path("library")
STYLES_DIR = LIBRARY_DIR / "styles"
CHARACTERS_DIR = LIBRARY_DIR / "characters"


def ensure_library_dirs() -> None:
    STYLES_DIR.mkdir(parents=True, exist_ok=True)
    CHARACTERS_DIR.mkdir(parents=True, exist_ok=True)


def _safe_id(value: str) -> str:
    cleaned = "".join(ch if ch.isalnum() or ch in ["-", "_"] else "-" for ch in value.strip())
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned.strip("-")


def style_profile_path(profile_id: str) -> Path:
    return STYLES_DIR / "profiles" / f"{_safe_id(profile_id)}.json"


def character_pack_path(pack_id: str) -> Path:
    return CHARACTERS_DIR / "packs" / f"{_safe_id(pack_id)}.json"


def ensure_subdirs() -> None:
    (STYLES_DIR / "profiles").mkdir(parents=True, exist_ok=True)
    (CHARACTERS_DIR / "packs").mkdir(parents=True, exist_ok=True)


def read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Invalid record format")
    return data


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def list_json_records(directory: Path) -> list[dict[str, Any]]:
    if not directory.exists():
        return []
    records: list[dict[str, Any]] = []
    for file_path in sorted(directory.glob("*.json")):
        try:
            records.append(read_json(file_path))
        except Exception:
            continue
    return records


def _write_preview_image(path: Path, title: str, subtitle: str, mode: str = "default") -> None:
    try:
        from PIL import Image, ImageDraw

        path.parent.mkdir(parents=True, exist_ok=True)
        image = Image.new("RGB", (1024, 576), color=(24, 28, 52))
        draw = ImageDraw.Draw(image)

        # layered panel background
        draw.rectangle((40, 40, 984, 536), fill=(35, 42, 78))
        draw.rectangle((60, 70, 964, 506), outline=(107, 139, 255), width=3)

        # Compose cloud/text style previews inspired by common comic bubble and word-art patterns.
        if mode == "cloud":
            draw.ellipse((220, 170, 820, 430), fill=(246, 248, 255), outline=(36, 42, 72), width=5)
            draw.ellipse((770, 400, 860, 470), fill=(246, 248, 255), outline=(36, 42, 72), width=4)
            draw.ellipse((840, 455, 900, 505), fill=(246, 248, 255), outline=(36, 42, 72), width=3)
            draw.text((300, 250), "Cloud + Text Preview", fill=(40, 56, 116))
            draw.text((270, 290), subtitle, fill=(70, 80, 122))
        elif mode == "wordart":
            draw.rectangle((220, 200, 820, 380), fill=(18, 22, 46), outline=(120, 152, 255), width=4)
            draw.text((280, 220), "WORD ART", fill=(255, 227, 92))
            draw.text((286, 224), "WORD ART", fill=(255, 110, 178))
            draw.text((306, 286), subtitle, fill=(199, 216, 255))
        else:
            draw.text((88, 112), title, fill=(132, 233, 255))
            draw.text((88, 170), subtitle, fill=(220, 228, 255))

        draw.text((88, 474), title, fill=(182, 195, 242))
        draw.text((88, 504), "Preview asset generated by CMiner style seeding", fill=(150, 165, 210))
        image.save(path)
    except Exception:
        # Preview generation is best-effort; registry still works without it.
        return


def _ensure_style_previews() -> None:
    preview_dir = STYLES_DIR / "previews"
    preview_specs = [
        ("cloud-fluffy.png", "Fluffy Speech Cloud", "Soft rounded speech bubble style", "cloud"),
        ("cloud-thought-neo.png", "Neo Thought Bubble", "Thought cloud with manga-tail style", "cloud"),
        ("render-cinematic-anime.png", "Cinematic Anime Render", "High contrast + dramatic composition", "default"),
        ("subtitle-neon-clean.png", "Neon Clean Subtitle", "Readable subtitle with clean stroke", "wordart"),
        ("font-inter-clean.png", "Inter Clean", "Readable modern font sample", "wordart"),
        ("font-roboto-broadcast.png", "Roboto Broadcast", "Broadcast subtitle font sample", "wordart"),
    ]

    for file_name, title, subtitle, mode in preview_specs:
        target = preview_dir / file_name
        if not target.exists():
            _write_preview_image(target, title, subtitle, mode)


def seed_default_styles() -> None:
    ensure_library_dirs()
    ensure_subdirs()
    _ensure_style_previews()

    default_profiles = [
        {
            "id": "font-inter-clean",
            "name": "Inter Clean",
            "category": "font",
            "version": "v1",
            "tags": ["modern", "readable"],
            "status": "active",
            "preview_assets": {
                "sample_text": "The quick brown fox jumps over the lazy dog.",
                "thumbnail": "library/styles/previews/font-inter-clean.png",
            },
            "config_json": {"family": "Inter", "weight": 500, "stroke": 1},
        },
        {
            "id": "font-roboto-broadcast",
            "name": "Roboto Broadcast",
            "category": "font",
            "version": "v1",
            "tags": ["broadcast", "subtitle"],
            "status": "active",
            "preview_assets": {
                "sample_text": "Signal is live and clear.",
                "thumbnail": "library/styles/previews/font-roboto-broadcast.png",
            },
            "config_json": {"family": "Roboto", "weight": 500, "stroke": 1},
        },
        {
            "id": "cloud-fluffy-default",
            "name": "Fluffy Speech Cloud",
            "category": "cloud",
            "version": "v1",
            "tags": ["speech", "friendly"],
            "status": "active",
            "preview_assets": {"thumbnail": "library/styles/previews/cloud-fluffy.png"},
            "config_json": {"shape": "soft-round", "tail": "speech"},
        },
        {
            "id": "cloud-thought-neo",
            "name": "Neo Thought Bubble",
            "category": "cloud",
            "version": "v1",
            "tags": ["thought", "manga"],
            "status": "active",
            "preview_assets": {"thumbnail": "library/styles/previews/cloud-thought-neo.png"},
            "config_json": {"shape": "cloud-dot-tail", "tail": "thought"},
        },
        {
            "id": "render-cinematic-anime-v1",
            "name": "Cinematic Anime Render",
            "category": "render",
            "version": "v1",
            "tags": ["anime", "cinematic"],
            "status": "active",
            "preview_assets": {"thumbnail": "library/styles/previews/render-cinematic-anime.png"},
            "config_json": {"prompt_suffix": "cinematic anime, volumetric light, dramatic composition"},
        },
        {
            "id": "subtitle-neon-clean",
            "name": "Neon Clean Subtitle",
            "category": "subtitle",
            "version": "v1",
            "tags": ["subtitle", "neon"],
            "status": "active",
            "preview_assets": {"thumbnail": "library/styles/previews/subtitle-neon-clean.png"},
            "config_json": {"font_size": 42, "outline": 2, "shadow": 1},
        },
    ]

    for profile in default_profiles:
        path = style_profile_path(profile["id"])
        if not path.exists():
            write_json(path, profile)
            continue

        existing = read_json(path)
        existing.setdefault("preview_assets", {})
        for key, value in profile.get("preview_assets", {}).items():
            existing["preview_assets"].setdefault(key, value)
        write_json(path, existing)
