import { BrowserRouter, Routes, Route, NavLink } from 'react-router-dom';
import { LayoutDashboard, FolderTree, PlaySquare, Settings, TerminalSquare } from 'lucide-react';
import './index.css';

import Sessions from './pages/Sessions';
import Agents from './pages/Agents';

// Placeholder Pages
const Dashboard = () => (
  <div className="animate-fade-in">
    <h1 style={{fontSize: '2rem', color: 'var(--text-accent)'}}>Studio Overview</h1>
    <p style={{color: 'var(--text-muted)', fontSize: '1.1rem'}}>Welcome to CMiner AI Content Studio.</p>
    
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '1.5rem', marginTop: '2rem' }}>
      <div className="glass-panel" style={{ padding: '1.5rem' }}>
        <h3>📁 Latest Sessions</h3>
        <p style={{color: 'var(--text-muted)'}}>Explore recent outputs generated by your agents.</p>
        <NavLink to="/sessions" className="btn btn-primary" style={{marginTop: '1rem'}}>Browse Files</NavLink>
      </div>
      <div className="glass-panel" style={{ padding: '1.5rem' }}>
        <h3>🤖 Agent Runner</h3>
        <p style={{color: 'var(--text-muted)'}}>Trigger a new background job and watch terminal logs.</p>
        <NavLink to="/agents" className="btn btn-primary" style={{marginTop: '1rem'}}>Execute</NavLink>
      </div>
    </div>
  </div>
);

const Editor = () => <div className="animate-fade-in"><h2>A/V Editor</h2><p>Timeline and compositing goes here.</p></div>;

const Layout = ({ children }) => {
  return (
    <div className="app-container">
      {/* Sidebar Navigation */}
      <aside className="sidebar">
        <div className="sidebar-header">
          <h2>CMiner Studio</h2>
        </div>
        <nav className="nav-links">
          <NavLink to="/" className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}>
            <LayoutDashboard size={20} /> Overview
          </NavLink>
          <NavLink to="/sessions" className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}>
            <FolderTree size={20} /> Sessions
          </NavLink>
          <NavLink to="/agents" className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}>
            <TerminalSquare size={20} /> Agents
          </NavLink>
          <NavLink to="/editor" className={({isActive}) => `nav-item ${isActive ? 'active' : ''}`}>
            <PlaySquare size={20} /> A/V Editor
          </NavLink>
        </nav>
        <div style={{ padding: '1rem', borderTop: '1px solid var(--border-color)', color: 'var(--text-muted)', fontSize: '0.8rem' }}>
          <Settings size={16} style={{display:'inline', marginRight:'8px', verticalAlign:'middle'}}/> Config
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="main-content">
        <header className="topbar">
          <div style={{ flex: 1 }}></div>
          <div style={{ fontSize: '0.875rem', color: 'var(--success)', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{width: 8, height: 8, borderRadius: '50%', background: 'currentColor', display: 'inline-block', boxShadow: '0 0 8px currentColor'}}></span> 
            API Connected
          </div>
        </header>
        <div className="workspace">
          {children}
        </div>
      </main>
    </div>
  );
};

function App() {
  return (
    <BrowserRouter>
      <Layout>
        <Routes>
          <Route path="/" element={<Dashboard />} />
          <Route path="/sessions" element={<Sessions />} />
          <Route path="/agents" element={<Agents />} />
          <Route path="/editor" element={<Editor />} />
          <Route path="*" element={<div>404 Not Found</div>} />
        </Routes>
      </Layout>
    </BrowserRouter>
  );
}

export default App;
